fmt

diff --git a/collate b/collate
--- a/collate
+++ b/collate
@@ -18,13 +18,7 @@ if [ -z "$output" ]; then
     output="collated.pdf"
 fi
 
-# verify dependencies
-hash convert 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS convert"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-    echo "whoops! missing dependencies:"
-    echo $MISSING_DEPS
-    exit
-fi
+hash convert 2>/dev/null || { echo "ERROR: missing dependencies: 'convert'" && exit 1; } # check dependencies
 
 convert "$1" $output
 echo "collate command finished. output: $output"
diff --git a/crop b/crop
--- a/crop
+++ b/crop
@@ -18,13 +18,7 @@ if [ -z "$1" ] || [ "$1" = "-h" ]; then
     echo "selected area 550px to right and 120px to bottom"
 fi
 
-# verify dependencies
-hash convert 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS convert"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-    echo "whoops! missing dependencies:"
-    echo $MISSING_DEPS
-    exit
-fi
+hash convert 2>/dev/null || { echo "ERROR: missing dependencies: 'convert'" && exit 1; } # check dependencies
 
 current_dir=$(pwd)
 
diff --git a/makegif b/makegif
--- a/makegif
+++ b/makegif
@@ -11,10 +11,10 @@ scale=${2:-${scale_default}}
 fps=${3:-${fps_default}}
 
 if [ -z "$1" ] || [ "$1" = "-h" ]; then
-	echo "$(basename $0) converts given video file to GIF using ffmpeg."
-	echo "GIF output will be stored in the same directory of video file."
-	echo "usage: $(basename $0) <video file> [scale] [fps]"
-	echo "examples:"
+	echo "$(basename $0) – converts given video file to GIF using ffmpeg."
+	echo "The output will be stored in the same directory of video file."
+	echo "Usage: $(basename $0) <video file> [scale] [fps]"
+	echo "Examples:"
 	echo "- convert video to GIF of default scale ($fps_default) & fps ($scale_default):"
 	echo "  $(basename $0) my-video.mp4"
 	echo "- specify custom scale & fps:"
@@ -22,13 +22,7 @@ if [ -z "$1" ] || [ "$1" = "-h" ]; then
 	exit
 fi
 
-# verify dependencies
-hash ffmpeg 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS ffmpeg"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-    echo "[ERROR] missing dependencies:"
-    echo $MISSING_DEPS
-    exit
-fi
+hash ffmpeg 2>/dev/null || { echo "ERROR: missing dependencies: 'ffmpeg'" && exit 1; } # check dependencies
 
 echo "[INFO] making gif.."
 echo "output file: $output_file"
@@ -53,15 +47,15 @@ filters="fps=${fps},scale=${scale}:-1:flags=lanczos"
 
 # create palette
 ffmpeg \
--i "$input_file" \
--loglevel panic -hide_banner -nostats \
--vf "$filters,palettegen" \
--y "$palette"
+	-i "$input_file" \
+	-loglevel panic -hide_banner -nostats \
+	-vf "$filters,palettegen" \
+	-y "$palette"
 
 # create gif
 ffmpeg \
--i "$input_file" \
--loglevel panic -hide_banner -nostats \
--i $palette \
--lavfi "$filters [x]; [x][1:v] paletteuse" \
--y "$output_file"
+	-i "$input_file" \
+	-loglevel panic -hide_banner -nostats \
+	-i $palette \
+	-lavfi "$filters [x]; [x][1:v] paletteuse" \
+	-y "$output_file"
diff --git a/makemp4 b/makemp4
--- a/makemp4
+++ b/makemp4
@@ -4,20 +4,15 @@ input_file=$1
 output_file="$1.mp4"
 
 if [ -z "$1" ] || [ "$1" = "-h" ]; then
-	echo "$(basename $0) converts given file (.mov, .gif, etc.) to .mp4 using ffmpeg."
-	echo "the output will be stored in the same directory of input file."
-	echo "usage: $(basename $0) <input file>"
-	echo "example: $(basename $0) my-screencast.mov"
-	exit
+  echo "$(basename $0) – converts given file (.mov, .gif, etc.) to .mp4 using ffmpeg."
+  echo "The output will be stored in the same directory of input file."
+  echo "Usage: $(basename $0) <input file>"
+  echo "Example: $(basename $0) my-screencast.mov"
+  exit
 fi
 
 # verify dependencies
-hash ffmpeg 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS ffmpeg"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-    echo "[ERROR] missing dependencies:"
-    echo $MISSING_DEPS
-    exit
-fi
+hash ffmpeg 2>/dev/null || { echo "ERROR: missing dependencies: 'ffmpeg'" && exit 1; } # check dependencies
 
 echo "[INFO] making mp4.."
 echo "output file: $output_file"
diff --git a/pdfencrypt b/pdfencrypt
--- a/pdfencrypt
+++ b/pdfencrypt
@@ -3,21 +3,15 @@
 # install pdfcpu: go get github.com/pdfcpu/pdfcpu/cmd/...
 # download pdfcpu binary: https://github.com/pdfcpu/pdfcpu/releases
 
-hash pdfcpu 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS pdfcpu"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-	echo "[ERROR] missing dependencies:"
-	echo $MISSING_DEPS
-	exit
-fi
+hash pdfcpu 2>/dev/null || { echo "ERROR: missing dependencies: 'pdfcpu'" && exit 1; } # check dependencies
 
-SCRIPT=$(basename $0)
 if [ -z "$1" ]; then
-    echo "$SCRIPT encrypts given pdf file using pdfcpu binary."
-    echo "usage: $SCRIPT <pdf file> [password. default to PDF_PASSWORD env]"
-    echo "example: $SCRIPT ~/Desktop/account-statement.pdf my-password"
+    echo "$(basename $0) encrypts given pdf file using pdfcpu binary."
+    echo "usage: $(basename $0) <pdf file> [password. default to PDF_PASSWORD env]"
+    echo "example: $(basename $0) ~/Desktop/account-statement.pdf my-password"
     echo ""
     echo "use '-r' to remove password protection from pdf file:"
-    echo "example: $SCRIPT <pdf file> -r [password]"
+    echo "example: $(basename $0) <pdf file> -r [password]"
     exit
 fi
 
