fmt

diff --git a/diffy b/diffy
--- a/diffy
+++ b/diffy
@@ -5,10 +5,10 @@
 # 2. copy or link this file to your path (ie. `ln -s diffy /usr/local/bin`)
 # 3. run diffy to upload your `git diff` to diffy
 if [ "$1" = "-h" ]; then
-    echo "diffy –– upload output of git diff to diffy.org"
-    echo "usage: diffy [diff command (optional)]"
+    echo "$(basename $0) – upload output of git diff to diffy.org"
+    echo "Usage: $(basename $0) [diff command (optional)]"
     echo ""
-    echo "examples:"
+    echo "Examples:"
     echo "- upload diff from 'git diff' of current directory:"
     echo "  diffy"
     echo "- upload diff from 'git diff' of files outside git repo:"
@@ -16,18 +16,14 @@ if [ "$1" = "-h" ]; then
     exit
 fi
 
-# verify dependencies
+# check dependencies
 hash git 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS git"; }
 hash curl 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS curl"; }
 hash xargs 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS xargs"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-    echo "whoops! missing dependencies:"
-    echo $MISSING_DEPS
-    exit
-fi
+[ ! -z "$MISSING_DEPS" ] && echo "ERROR: missing dependencies: ${MISSING_DEPS}" && exit 1
 
 # ensure current dir is git repo if `--no-index` is not used
-if [ "$2" != "--no-index" ] && [ ! git rev-parse --git-dir > /dev/null 2>&1 ]; then
+if [ "$2" != "--no-index" ] && [ ! git rev-parse --git-dir ] >/dev/null 2>&1; then
     echo "diffy error: directory is not git repo"
     exit
 fi
@@ -36,7 +32,7 @@ fi
 DIFF_FILE=/tmp/to_diffy.diff
 
 DIFF_COMMAND=$(echo "git diff $@" | xargs)
-`$DIFF_COMMAND > $DIFF_FILE`
+$($DIFF_COMMAND >$DIFF_FILE)
 
 if [ -z "$(cat $DIFF_FILE)" ]; then
     echo "command '$DIFF_COMMAND' returns empty output. exiting."
@@ -47,9 +43,9 @@ echo "uploading output of '$DIFF_COMMAND' to diffy.org.."
 
 # sample response:
 # Found. Redirecting to /diff/4hrag1lvv7lgyt81v6t0fqolxr
-diffy_response=`curl -s -F diffFile=@$DIFF_FILE https://diffy.org/new`
+diffy_response=$(curl -s -F diffFile=@$DIFF_FILE https://diffy.org/new)
 
-# shell won't understand below string substition. 
+# shell won't understand below string substition.
 # use bash instead.
 replacer=https\://diffy.org/diff
 echo "${diffy_response/\/diff/$replacer}"
diff --git a/ocr b/ocr
--- a/ocr
+++ b/ocr
@@ -25,24 +25,20 @@ __extract_text() {
 }
 
 if [ -z "$1" ] || [ "$1" = "-h" ] || [ -z "$2" ]; then
-    echo "ocr –– run ocr on given file (or files in directory)"
-    echo "usage: ocr <path to file or directory> <output dir>"
-    echo "example: ocr ~/Downloads/my-document.jpg ."
+    echo "$(basename $0) – run ocr on given file (or files in directory)"
+    echo "Usage: $(basename $0) <path to file or directory> <output dir>"
+    echo "Example: $(basename $0) ~/my-document.jpg ."
     exit
 fi
 
-# verify dependencies
+# check dependencies
 hash convert 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS convert"; }
 hash tesseract 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS tesseract"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-    echo "whoops! missing dependencies:"
-    echo $MISSING_DEPS
-    exit
-fi
+[ ! -z "$MISSING_DEPS" ] && echo "ERROR: missing dependencies: ${MISSING_DEPS}" && exit 1
 
 # handle directory
-if [ -d "$1" ] ; then
-    for file in "$1"/*.{jpg,jpeg,png} ; do
+if [ -d "$1" ]; then
+    for file in "$1"/*.{jpg,jpeg,png}; do
         # don't process if filename begins with "*."
         if [[ $file = *"/*."* ]]; then
             continue
@@ -69,7 +65,7 @@ if [ -f "$1" ]; then
     else
         echo "File not supported. Only jpg, jpeg & png are supported."
     fi
-exit
+    exit
 fi
 
 echo "operation failed: unhandled error"
diff --git a/ytmp3 b/ytmp3
--- a/ytmp3
+++ b/ytmp3
@@ -12,11 +12,11 @@
 
 # display usage info
 if [ "$1" == "-h" ] || [ -z "$1" ]; then
-    echo "ytmp3 –– download youtube video and convert to mp3"
-    echo "usage: ytmp3 <youtube url/video id> <output dir>"
+    echo "$(basename $0) – download youtube video and convert to mp3"
+    echo "usage: $(basename $0) <youtube url/video id> <output dir>"
     echo "example:"
-    echo "- ytmp3 RXARHZmpgvw ~/Downloads/"
-    echo "- ytmp3 https://www.youtube.com/watch?v=p29JUpsOSTE ~/Downloads/"
+    echo "- $(basename $0) RXARHZmpgvw ~/Downloads/"
+    echo "- $(basename $0) https://www.youtube.com/watch?v=p29JUpsOSTE ~/Downloads/"
     exit
 fi
 
@@ -33,14 +33,10 @@ if [ "$OUTPUT_DIR" != "" ] && [[ "$OUTPUT_DIR" != */ ]]; then
     OUTPUT_DIR="${OUTPUT_DIR}/"
 fi
 
-# verify dependencies
+# check dependencies
 hash ytdl 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS ytdl"; }
 hash ffmpeg 2>/dev/null || { MISSING_DEPS="$MISSING_DEPS ffmpeg"; }
-if [ ! -z "$MISSING_DEPS" ]; then
-    echo "whoops! missing dependencies:"
-    echo $MISSING_DEPS
-    exit 2
-fi
+[ ! -z "$MISSING_DEPS" ] && echo "ERROR: missing dependencies: ${MISSING_DEPS}" && exit 1
 
 # use ytdl to fetch video info.
 # using ytdl v0.5.0, the info would look like this:
@@ -54,7 +50,7 @@ fi
 # the `awk -F': ' 'NR == 1 {print $2}'` will get the first
 # line of video info ('NR == 1'), and take the part of
 # line that comes after ': ' (-F': ').
-FILENAME=`ytdl --info $1 | awk -F': ' 'NR == 1 {print $2}'`
+FILENAME=$(ytdl --info $1 | awk -F': ' 'NR == 1 {print $2}')
 if [ -z "$FILENAME" ]; then
     echo "Download failed: video id '$1' is invalid"
     exit 3
