Store result in json file (1 minute cache). Add link to search the query in lexica.art.

diff --git a/lexicat b/lexicat
--- a/lexicat
+++ b/lexicat
@@ -13,11 +13,20 @@ IMGCAT=~/.iterm2/imgcat
 
 hash curl 2>/dev/null || { echo "ERROR: missing dependencies: 'curl'" && exit 1; } # check dependencies
 hash jq 2>/dev/null || { echo "ERROR: missing dependencies: 'jq'" && exit 1; }
+hash md5 2>/dev/null || { echo "ERROR: missing dependencies: 'md5'" && exit 1; }
+hash date 2>/dev/null || { echo "ERROR: missing dependencies: 'date'" && exit 1; }
 
 base_url="https://lexica.art/api/v1/search"
+query="$@"
 
-# Get images from Lexica API
-json=$(curl --silent --get --data-urlencode "q=$@" "$base_url")
+# Prepare json file for cache
+file_suffix="$(date +%F-%H-%M)-$(echo '$query' | md5)"
+json_file="/tmp/lexicat-${file_suffix}.json"
+
+# Get images from Lexica API for new query
+[ ! -f "$json_file" ] && curl --silent --get --data-urlencode "q=$@" "$base_url" >"$json_file"
+
+json=$(cat $json_file)
 count_images=$(echo $json | jq '.images | length')
 
 # Pick random image from json
@@ -32,4 +41,10 @@ curl -o /tmp/lexicat --silent $thumbnail_url
 $IMGCAT -H 250px /tmp/lexicat
 
 view_url="https://lexica.art/prompt/$prompt_id"
-echo "View in browser: $view_url"
+
+encode_query=$(curl -s -w '%{url}\n' -G / --data-urlencode "=$query" | cut -c 3-)
+search_url="https://lexica.art/?q=$encode_query"
+
+echo "- 📁 JSON file: $json_file"
+echo "- 🌐 View in browser: $view_url"
+echo "- 🔍 Search in lexica.art: $search_url"
